name: DavidArt
favicon: null
layout_spectrum: 0.9976848419755697
typography_spectrum: 0.7504959739744663
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b64000'
    - '#791c00'
    - '#b79b76'
    - '#72512e'
    - '#a65e15'
  brandStrength: 0.9505323828198016
  lightness: 0.2623197119683027
  saturation: 0.5258932262659073
  rhythmicContrast: 0.75
purpose: []
