typography_spectrum: 0.75255
color:
  brandColors:
    - '#b64000'
    - '#791c00'
    - '#b79b76'
    - '#72512e'
    - '#a65e15'
  brandStrength: 0.9505323828198016
  lightness: 0.2623197119683027
  saturation: 0.5258932262659073
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: DavidArt
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: David A. Meyer II
purpose: []
